### ISSUE TITLE
ModuleNotFoundError: No module named 'winreg'

### ISSUE THREAD

**Issue by shanto** [zen-browser/desktop#1845]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I spotted this error about **winreg** several times during my github builds and thought to report it in case it breaks any feature/functionality.

```00:01:58 Traceback (most recent call last):
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/configure.py", line 351, in <module>
00:01:58     sys.exit(main(sys.argv))
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/configure.py", line 141, in main
00:01:58     sandbox.run()
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 573, in run
00:01:58     func(*args)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 624, in _value_for
00:01:58     return self._value_for_depends(obj)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/util.py", line 916, in method_call
00:01:58     cache[args] = self.func(instance, *args)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 633, in _value_for_depends
00:01:58     value = obj.result()
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/util.py", line 916, in method_call
00:01:58     cache[args] = self.func(instance, *args)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 162, in result
00:01:58     return self._func(*resolved_args)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 1316, in wrapped
00:01:58     return new_func(*args, **kwargs)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/build/moz.configure/windows.configure", line 54, in windows_sdk_dir
00:01:58     for x in get_registry_values(
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 1315, in wrapped
00:01:58     self._apply_imports(func, glob)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 976, in _apply_imports
00:01:58     self._get_one_import(_from, _import, _as, glob)
00:01:58   File "/home/runner/work/zen-desktop/zen-desktop/engine/python/mozbuild/mozbuild/configure/__init__.py", line 1111, in _get_one_import
00:01:58     exec(import_line, {}, glob)
00:01:58   File "<string>", line 1, in <module>
00:01:58 ModuleNotFoundError: No module named 'winreg'
```

[Full Trace](https://github.com/shanto/zen-desktop/actions/runs/11124787603/job/30918700235#step:20:2166)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

master

### What platform are you seeing the problem on?

Windows

**Comment by anatasiajp** [comment]
winreg is for Windows, in production Zen there's no such issue.

It's mostly harmless.
