### ISSUE TITLE
MakeNSIS is found but the build fails while getting it's version.

### ISSUE THREAD

**Issue by luiggircardoso** [zen-browser/desktop#4056]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

MakeNSIS makes the build fails while getting it's version. No reason is given, the file is on the right path on .mozbuild and the build process still fails after running `npm run bootstrap`.

I also tried running it from terminal like normally and it also returned an error.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
./mach build
 0:02.15 W Clobber not needed.
 Config object not found by mach.
 0:03.10 Using Python 3.13.1 from C:\Users\Usuario\.mozbuild\srcdirs\engine-83b8a28e9bdd\_virtualenvs\build\Scripts\python.exe
 0:03.10 Adding configure options from C:\Users\Usuario\Desktop\Projetos\desktop\engine\mozconfig
 0:03.10   --with-app-name=zen
 0:03.10   --with-app-basename=Zen
 0:03.10   --enable-official-branding
 0:03.11   --enable-application=browser
 0:03.11   --enable-unverified-updates
 0:03.11   --enable-raw
 0:03.11   --enable-webrtc
 0:03.12   --enable-jxl
 0:03.12   --enable-av1
 0:03.12   --with-unsigned-addon-scopes=app,system
 0:03.12   --disable-maintenance-service
 0:03.13   --disable-bits-download
 0:03.13   --disable-clang-plugin
 0:03.13   --disable-debug
 0:03.13   --with-branding=browser/branding/unofficial
 0:03.13   --enable-unverified-updates
 0:03.14   --enable-update-channel=unofficial
 0:03.14   MOZ_APP_PROFILE=zen
 0:03.14   MOZ_BRANDING_DIRECTORY=branding/unofficial
 0:03.14   MOZ_SOURCE_CHANGESET=f241bfb7b8f57b670e9210ea33db72846a0f2453
 0:03.14   MOZ_SOURCE_REPO=https://github.com/luiggircardoso/desktop
 0:03.14   ZEN_FIREFOX_VERSION=133.0.3
 0:03.14   MOZ_INCLUDE_SOURCE_INFO=1
 0:03.14   MOZ_APP_DISPLAYNAME=Zen Browser
 0:03.15   MOZ_APPUPDATE_HOST=updates.zen-browser.app
 0:03.15   MOZ_USER_DIR=Zen Browser
 0:03.15   MOZ_APP_BASENAME=Zen
 0:03.15   MOZ_REQUIRE_SIGNING=
 0:03.15   MOZ_DISTRIBUTION_ID=com.zen.browser
 0:03.15   VERBOSE=1
 0:03.15   MOZ_OFFICIAL_BRANDING_DIRECTORY=branding/unofficial
 0:03.15 checking for vcs source checkout... git
 0:03.21 checking for a shell... C:/mozilla-build/msys2/usr/bin/sh.exe
 0:03.21 checking for host system type... x86_64-pc-windows-msvc
 0:03.21 checking for target system type... x86_64-pc-windows-msvc
 0:03.57 checking whether cross compiling... no
 0:03.70 checking for Python 3... C:/Users/Usuario/.mozbuild/srcdirs/engine-83b8a28e9bdd/_virtualenvs/build/Scripts/python.exe (3.13.1)
 0:03.70 checking for git... C:/Users/Usuario/scoop/apps/git/2.47.1/mingw64/bin/git.exe
 0:03.73 checking for Git version... 2.47.1.windows.1
 0:03.73 checking for MozillaBuild directory... C:\mozilla-build
 0:03.73 checking for MozillaBuild version... 4.1
 0:03.75 checking for wget... C:/mozilla-build/msys2/usr/bin/wget.exe
 0:03.75 checking for ccache... not found
 0:03.75 checking for the target C compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang-cl.exe
 0:03.89 checking whether the target C compiler can be used... yes
 0:03.89 checking the target C compiler version... 18.1.7
 0:03.95 checking the target C compiler works... yes
 0:03.95 checking for the target C++ compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang-cl.exe
 0:04.05 checking whether the target C++ compiler can be used... yes
 0:04.05 checking the target C++ compiler version... 18.1.7
 0:04.11 checking the target C++ compiler works... yes
 0:04.11 checking for the host C compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang-cl.exe
 0:04.11 checking whether the host C compiler can be used... yes
 0:04.11 checking the host C compiler version... 18.1.7
 0:04.11 checking the host C compiler works... yes
 0:04.11 checking for the host C++ compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang-cl.exe
 0:04.11 checking whether the host C++ compiler can be used... yes
 0:04.12 checking the host C++ compiler version... 18.1.7
 0:04.12 checking the host C++ compiler works... yes
 0:04.17 checking for 64-bit OS... yes
 0:04.27 checking for Windows SDK... 0x0a00 in 'C:/Users/Usuario/.mozbuild/vs/Windows Kits/10'
 0:04.27 checking for Universal CRT SDK... 10.0.22621.0 in 'C:/Users/Usuario/.mozbuild/vs/Windows Kits/10'
 0:04.37 checking for linker... C:/Users/Usuario/.mozbuild/clang/bin/lld-link.exe
 0:04.37 checking for host_linker... C:/Users/Usuario/.mozbuild/clang/bin/lld-link.exe
 0:04.39 checking for the assembler... C:/Users/Usuario/.mozbuild/vs/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/ml64.exe
 0:04.44 checking for llvm-objdump... C:/Users/Usuario/.mozbuild/clang/bin/llvm-objdump.exe
 0:04.44 checking for rc... C:/Users/Usuario/.mozbuild/clang/bin/llvm-rc.exe
 0:04.44 checking for ar... C:/Users/Usuario/.mozbuild/clang/bin/llvm-lib.exe
 0:04.52 checking whether ar supports response files... no
 0:04.52 checking for host_ar... C:/Users/Usuario/.mozbuild/clang/bin/llvm-lib.exe
 0:04.58 checking for -mavxvnni support... yes
 0:04.63 checking for -mavx512bw support... yes
 0:04.69 checking for -mavx512vnni support... yes
 0:04.76 checking for malloc.h... yes
 0:04.82 checking for stdint.h... yes
 0:04.88 checking for inttypes.h... yes
 0:04.93 checking for alloca.h... no
 0:04.98 checking for sys/byteorder.h... no
 0:05.03 checking for getopt.h... no
 0:05.09 checking for unistd.h... no
 0:05.14 checking for nl_types.h... no
 0:05.20 checking for cpuid.h... yes
 0:05.25 checking for fts.h... no
 0:05.30 checking for sys/statvfs.h... no
 0:05.36 checking for sys/statfs.h... no
 0:05.41 checking for sys/vfs.h... no
 0:05.47 checking for sys/mount.h... no
 0:05.52 checking for sys/quota.h... no
 0:05.59 checking for sys/queue.h... no
 0:05.65 checking for sys/types.h... yes
 0:05.70 checking for netinet/in.h... no
 0:05.76 checking for byteswap.h... no
 0:05.82 checking for memfd_create in sys/mman.h... no
 0:05.88 checking whether the C compiler supports -Wbitfield-enum-conversion... yes
 0:05.93 checking whether the C++ compiler supports -Wbitfield-enum-conversion... yes
 0:05.99 checking whether the C compiler supports -Wformat-type-confusion... yes
 0:06.04 checking whether the C++ compiler supports -Wformat-type-confusion... yes
 0:06.10 checking whether the C compiler supports -Wshadow-field-in-constructor-modified... yes
 0:06.17 checking whether the C++ compiler supports -Wshadow-field-in-constructor-modified... yes
 0:06.23 checking whether the C compiler supports -Wtautological-constant-in-range-compare... yes
 0:06.29 checking whether the C++ compiler supports -Wtautological-constant-in-range-compare... yes
 0:06.34 checking whether the C compiler supports -Wno-error=tautological-type-limit-compare... yes
 0:06.39 checking whether the C++ compiler supports -Wno-error=tautological-type-limit-compare... yes
 0:06.45 checking whether the C compiler supports -Wunreachable-code-return... yes
 0:06.50 checking whether the C++ compiler supports -Wunreachable-code-return... yes
 0:06.56 checking whether the C compiler supports -Wunused-but-set-parameter... yes
 0:06.61 checking whether the C++ compiler supports -Wunused-but-set-parameter... yes
 0:06.67 checking whether the C compiler supports -Wclass-varargs... yes
 0:06.72 checking whether the C++ compiler supports -Wclass-varargs... yes
 0:06.78 checking whether the C++ compiler supports -Wempty-init-stmt... yes
 0:06.83 checking whether the C compiler supports -Wfloat-overflow-conversion... yes
 0:06.89 checking whether the C++ compiler supports -Wfloat-overflow-conversion... yes
 0:06.94 checking whether the C compiler supports -Wfloat-zero-conversion... yes
 0:07.00 checking whether the C++ compiler supports -Wfloat-zero-conversion... yes
 0:07.05 checking whether the C compiler supports -Wloop-analysis... yes
 0:07.11 checking whether the C++ compiler supports -Wloop-analysis... yes
 0:07.16 checking whether the C compiler supports -Wno-range-loop-analysis... yes
 0:07.22 checking whether the C++ compiler supports -Wno-range-loop-analysis... yes
 0:07.26 checking whether the C++ compiler supports -Wcomma-subscript... no
 0:07.31 checking whether the C compiler supports -Wenum-compare-conditional... yes
 0:07.37 checking whether the C++ compiler supports -Wenum-compare-conditional... yes
 0:07.42 checking whether the C compiler supports -Wenum-float-conversion... yes
 0:07.48 checking whether the C++ compiler supports -Wenum-float-conversion... yes
 0:07.53 checking whether the C++ compiler supports -Wvolatile... yes
 0:07.59 checking whether the C++ compiler supports -Wno-deprecated-anon-enum-enum-conversion... yes
 0:07.64 checking whether the C++ compiler supports -Wno-deprecated-enum-enum-conversion... yes
 0:07.70 checking whether the C++ compiler supports -Wno-deprecated-this-capture... yes
 0:07.75 checking whether the C++ compiler supports -Wcomma... yes
 0:07.79 checking whether the C compiler supports -Wduplicated-cond... no
 0:07.84 checking whether the C++ compiler supports -Wduplicated-cond... no
 0:07.89 checking whether the C++ compiler supports -Wimplicit-fallthrough... yes
 0:07.93 checking whether the C compiler supports -Wlogical-op... no
 0:07.97 checking whether the C++ compiler supports -Wlogical-op... no
 0:08.03 checking whether the C compiler supports -Wstring-conversion... yes
 0:08.09 checking whether the C++ compiler supports -Wstring-conversion... yes
 0:08.14 checking whether the C++ compiler supports -Wno-inline-new-delete... yes
 0:08.19 checking whether the C compiler supports -Wno-error=maybe-uninitialized... no
 0:08.23 checking whether the C++ compiler supports -Wno-error=maybe-uninitialized... no
 0:08.28 checking whether the C compiler supports -Wno-error=deprecated-declarations... yes
 0:08.34 checking whether the C++ compiler supports -Wno-error=deprecated-declarations... yes
 0:08.39 checking whether the C compiler supports -Wno-error=array-bounds... yes
 0:08.45 checking whether the C++ compiler supports -Wno-error=array-bounds... yes
 0:08.50 checking whether the C compiler supports -Wno-error=free-nonheap-object... yes
 0:08.56 checking whether the C++ compiler supports -Wno-error=free-nonheap-object... yes
 0:08.60 checking whether the C compiler supports -Wno-multistatement-macros... no
 0:08.65 checking whether the C++ compiler supports -Wno-multistatement-macros... no
 0:08.69 checking whether the C compiler supports -Wno-error=class-memaccess... no
 0:08.73 checking whether the C++ compiler supports -Wno-error=class-memaccess... no
 0:08.79 checking whether the C compiler supports -Wno-error=atomic-alignment... yes
 0:08.84 checking whether the C++ compiler supports -Wno-error=atomic-alignment... yes
 0:08.90 checking whether the C compiler supports -Wno-error=deprecated-builtins... yes
 0:08.95 checking whether the C++ compiler supports -Wno-error=deprecated-builtins... yes
 0:09.02 checking whether the C compiler supports -Wno-unknown-pragmas... yes
 0:09.08 checking whether the C++ compiler supports -Wno-unknown-pragmas... yes
 0:09.14 checking whether the C compiler supports -Wno-ignored-pragmas... yes
 0:09.19 checking whether the C++ compiler supports -Wno-ignored-pragmas... yes
 0:09.25 checking whether the C compiler supports -Wno-deprecated-declarations... yes
 0:09.30 checking whether the C++ compiler supports -Wno-deprecated-declarations... yes
 0:09.36 checking whether the C++ compiler supports -Wno-microsoft-enum-value... yes
 0:09.41 checking whether the C++ compiler supports -Wno-microsoft-include... yes
 0:09.47 checking whether the C compiler supports -Wno-invalid-noreturn... yes
 0:09.52 checking whether the C++ compiler supports -Wno-invalid-noreturn... yes
 0:09.58 checking whether the C++ compiler supports -Wno-inconsistent-missing-override... yes
 0:09.63 checking whether the C++ compiler supports -Wno-implicit-exception-spec-mismatch... yes
 0:09.69 checking whether the C++ compiler supports -Wno-microsoft-exception-spec... yes
 0:09.76 checking whether the C++ compiler supports -Wno-unused-local-typedef... yes
 0:09.82 checking whether the C++ compiler supports -Wno-ignored-attributes... yes
 0:09.88 checking whether the C++ compiler supports -Wno-used-but-marked-unused... yes
 0:09.94 checking whether the C compiler supports -Werror=implicit-function-declaration... yes
 0:09.99 checking whether the C compiler supports -Wno-psabi... yes
 0:10.05 checking whether the C++ compiler supports -Wno-psabi... yes
 0:10.11 checking whether the C compiler supports -Wthread-safety... yes
 0:10.16 checking whether the C++ compiler supports -Wthread-safety... yes
 0:10.22 checking whether the C compiler supports -Wno-error=builtin-macro-redefined... yes
 0:10.27 checking whether the C++ compiler supports -Wno-error=builtin-macro-redefined... yes
 0:10.33 checking whether the C++ compiler supports -Wno-vla-cxx-extension... yes
 0:10.38 checking whether the C compiler supports -Wno-unknown-warning-option... yes
 0:10.43 checking whether the C++ compiler supports -Wno-unknown-warning-option... yes
 0:10.48 checking whether the C++ compiler supports -fno-sized-deallocation... no
 0:10.52 checking whether the C++ compiler supports -fno-aligned-new... no
 0:10.72 checking what kind of list files are supported by the linker... list
 0:10.72 checking for llvm_profdata... C:/Users/Usuario/.mozbuild/clang/bin/llvm-profdata.exe
 0:10.74 checking whether llvm-profdata supports 'order' subcommand... yes
 0:10.85 checking for rustc... C:/Users/Usuario/.cargo/bin/rustc.exe
 0:10.85 checking for cargo... C:/Users/Usuario/.cargo/bin/cargo.exe
 0:10.97 Actually using 'C:\Users\Usuario\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\rustc.exe'
 0:11.09 Actually using 'C:\Users\Usuario\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe'
 0:11.11 checking rustc version... 1.83.0
 0:11.14 checking cargo version... 1.83.0
 0:11.31 checking for rust host triplet... x86_64-pc-windows-msvc
 0:11.43 checking for rust target triplet... x86_64-pc-windows-msvc
 0:11.44 checking for rustdoc... C:/Users/Usuario/.cargo/bin/rustdoc.exe
 0:11.48 checking for cbindgen... C:/Users/Usuario/.mozbuild/cbindgen/cbindgen.exe
 0:11.48 checking for rustfmt... C:/Users/Usuario/.cargo/bin/rustfmt.exe
 0:11.61 checking for clang for bindgen... C:/Users/Usuario/.mozbuild/clang/bin/clang.exe
 0:11.65 checking for libclang for bindgen... C:/Users/Usuario/.mozbuild/clang/bin/libclang.dll
 0:11.65 checking that libclang is new enough... yes
 0:11.65 checking bindgen cflags... -x c++ -fno-sized-deallocation -fno-aligned-new -DTRACING=1 -DIMPL_LIBXUL -DMOZILLA_INTERNAL_API -DRUST_BINDGEN -DWIN32=1 -D_CRT_USE_BUILTIN_OFFSETOF -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE=1 -std=gnu++17
 0:11.72 checking for tm_zone and tm_gmtoff in struct tm... no
 0:11.91 checking for _getc_nolock... yes
 0:12.09 checking for localeconv... yes
 0:12.12 checking for nodejs... C:\Users\Usuario\.mozbuild\node\node.EXE (18.19.0)
 0:12.16 checking for tar... C:/Users/Usuario/scoop/apps/git/2.47.1/usr/bin/tar.exe
 0:12.16 checking for unzip... C:/Users/Usuario/scoop/apps/git/2.47.1/usr/bin/unzip.exe
 0:12.16 checking for the Mozilla API key... no
 0:12.16 checking for the Google Location Service API key... no
 0:12.16 checking for the Google Safebrowsing API key... no
 0:12.17 checking for the Bing API key... no
 0:12.17 checking for the Adjust SDK key... no
 0:12.17 checking for the Leanplum SDK key... no
 0:12.17 checking for the Pocket API key... no
 0:12.18 checking for midl... 'C:/Users/Usuario/.mozbuild/vs/Windows Kits/10/bin/10.0.22621.0/x64/midl.exe'
 0:12.19 checking for llvm-dlltool... C:/Users/Usuario/.mozbuild/clang/bin/llvm-dlltool.exe
 0:12.20 checking for fxc... 'C:/Users/Usuario/.mozbuild/vs/Windows Kits/10/bin/10.0.22621.0/x64/fxc.exe'
 0:12.21 checking for nasm... C:/Users/Usuario/.mozbuild/nasm/nasm.exe
 0:12.22 checking nasm version... 2.15.05
 0:12.22 Using wasi sysroot in C:/Users/Usuario/.mozbuild/sysroot-wasm32-wasi
 0:12.22 checking for the wasm C compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang.exe
 0:12.30 checking whether the wasm C compiler can be used... yes
 0:12.30 checking the wasm C compiler version... 18.1.7
 0:12.35 checking the wasm C compiler works... yes
 0:12.39 checking the wasm C compiler can find wasi headers... yes
 0:12.52 checking the wasm C linker can find wasi libraries... yes
 0:12.52 checking for the wasm C++ compiler... C:/Users/Usuario/.mozbuild/clang/bin/clang++.exe
 0:12.65 checking whether the wasm C++ compiler can be used... yes
 0:12.65 checking the wasm C++ compiler version... 18.1.7
 0:12.70 checking the wasm C++ compiler works... yes
 0:12.76 checking the wasm C++ compiler can find wasi headers... yes
 0:12.91 checking the wasm C++ linker can find wasi libraries... yes
 0:12.99 checking for clock() in wasi sysroot... no
 0:13.12 checking for emulated clock() in wasi sysroot... yes
 0:13.12 checking for dump_syms... C:/Users/Usuario/.mozbuild/dump_syms/dump_syms.exe
 0:13.14 checking for pdbstr... 'C:/Users/Usuario/.mozbuild/vs/Windows Kits/10/Debuggers/x64/srcsrv/pdbstr.exe'
 0:13.14 checking for winchecksec... C:/Users/Usuario/.mozbuild/winchecksec/winchecksec.exe
 0:13.20 checking for sin_len in struct sockaddr_in... no
 0:13.26 checking for sin_len6 in struct sockaddr_in6... no
 0:13.31 checking for sa_len in struct sockaddr... no
 0:13.37 checking for pthread_cond_timedwait_monotonic_np... no
 0:13.43 checking for the windows rust crate source... C:/Users/Usuario/.mozbuild/windows-rs
 0:13.52 checking for valid C compiler optimization flags... yes
 0:13.52 checking for awk... C:/mozilla-build/msys2/usr/bin/gawk.exe
 0:13.52 checking for gmake... C:/Users/Usuario/.mozbuild/mozmake/mozmake.exe
 0:13.56 checking for watchman... C:/mozilla-build/bin/watchman.exe
 0:13.56 checking for watchman version... 20220410.024423.0
 0:13.57 checking for xargs... C:/Users/Usuario/scoop/apps/git/2.47.1/usr/bin/xargs.exe
 0:13.57 checking for makensisu... C:/Users/Usuario/.mozbuild/nsis/bin/makensis
 0:13.57 checking for NSIS version...
 0:13.57 DEBUG: Executing: `C:/Users/Usuario/.mozbuild/nsis/bin/makensis -version`
 0:13.57 Traceback (most recent call last):
 0:13.58   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\configure.py", line 345, in <module>
 0:13.58     sys.exit(main(sys.argv))
 0:13.58              ~~~~^^^^^^^^^^
 0:13.58   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\configure.py", line 140, in main
 0:13.58     sandbox.run()
 0:13.58     ~~~~~~~~~~~^^
 0:13.58   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 573, in run
 0:13.59     func(*args)
 0:13.59     ~~~~^^^^^^^
 0:13.59   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 624, in _value_for
 0:13.59     return self._value_for_depends(obj)
 0:13.59            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
 0:13.59   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\util.py", line 917, in method_call
 0:13.59     cache[args] = self.func(instance, *args)
 0:13.59                   ~~~~~~~~~^^^^^^^^^^^^^^^^^
 0:13.60   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 633, in _value_for_depends
 0:13.60     value = obj.result()
 0:13.60   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\util.py", line 917, in method_call
 0:13.60     cache[args] = self.func(instance, *args)
 0:13.60                   ~~~~~~~~~^^^^^^^^^^^^^^^^^
 0:13.60   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 162, in result
 0:13.61     return self._func(*resolved_args)
 0:13.61            ~~~~~~~~~~^^^^^^^^^^^^^^^^
 0:13.61   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1316, in wrapped
 0:13.61     return new_func(*args, **kwargs)
 0:13.61   File "C:/Users/Usuario/Desktop/Projetos/desktop/engine/build/moz.configure/util.configure", line 492, in wrapper
 0:13.61     return func(*args)
 0:13.61   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1316, in wrapped
 0:13.61     return new_func(*args, **kwargs)
 0:13.62   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 916, in wrapper
 0:13.62     ret = template(*args, **kwargs)
 0:13.62   File "C:/Users/Usuario/Desktop/Projetos/desktop/engine/build/moz.configure/checks.configure", line 59, in wrapped
 0:13.62     ret = func(*args, **kwargs)
 0:13.62   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1316, in wrapped
 0:13.62     return new_func(*args, **kwargs)
 0:13.62   File "C:/Users/Usuario/Desktop/Projetos/desktop/engine/moz.configure", line 706, in nsis_version
 0:13.63     out = check_cmd_output(nsis, "-version", onerror=onerror)
 0:13.63   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1316, in wrapped
 0:13.63     return new_func(*args, **kwargs)
 0:13.63   File "C:/Users/Usuario/Desktop/Projetos/desktop/engine/build/moz.configure/util.configure", line 57, in check_cmd_output
 0:13.63     retcode, stdout, stderr = get_cmd_output(*args, **kwargs)
 0:13.63                               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
 0:13.64   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1316, in wrapped
 0:13.64     return new_func(*args, **kwargs)
 0:13.64   File "C:/Users/Usuario/Desktop/Projetos/desktop/engine/build/moz.configure/util.configure", line 31, in get_cmd_output
 0:13.64     proc = subprocess.Popen(
 0:13.64         args,
 0:13.64     ...<8 lines>...
 0:13.64         **kwargs,
 0:13.64     )
 0:13.65   File "C:\Users\Usuario\Desktop\Projetos\desktop\engine\python\mozbuild\mozbuild\configure\__init__.py", line 1045, in wrapper
 0:13.65     return function(*args, **kwargs)
 0:13.65   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1036, in __init__
 0:13.65     self._execute_child(args, executable, preexec_fn, close_fds,
 0:13.65     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:13.65                         pass_fds, cwd, env,
 0:13.65                         ^^^^^^^^^^^^^^^^^^^
 0:13.66     ...<5 lines>...
 0:13.66                         gid, gids, uid, umask,
 0:13.66                         ^^^^^^^^^^^^^^^^^^^^^^
 0:13.66                         start_new_session, process_group)
 0:13.66                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:13.66   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1548, in _execute_child
 0:13.66     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
 0:13.67                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
 0:13.67                              # no special security
 0:13.67                              ^^^^^^^^^^^^^^^^^^^^^
 0:13.67     ...<4 lines>...
 0:13.67                              cwd,
 0:13.67                              ^^^^
 0:13.67                              startupinfo)
 0:13.67                              ^^^^^^^^^^^^
 0:13.67 OSError: [WinError 193] %1 não é um aplicativo Win32 válido
*** Fix above errors and then restart with "./mach build"
```

**Comment by luiggircardoso** [comment]
> Hi, [@luiggircardoso](https://github.com/luiggircardoso). I'm [Dosu](https://dosu.dev), and I'm helping the desktop team manage their backlog. I'm marking this issue as stale.
> 
> **Issue Summary:**
> 
>     * Encountering a build failure on Windows related to MakeNSIS.
> 
>     * Build process cannot retrieve the version of MakeNSIS, despite correct file location.
> 
>     * Attempts to resolve by running `npm run bootstrap` and building from the terminal were unsuccessful.
> 
>     * No specific error message provided to indicate the cause.
> 
>     * No comments or developments have been made on this issue yet.
> 
> 
> **Next Steps:**
> 
>     * Please confirm if this issue is still relevant with the latest version of the desktop repository by commenting here.
> 
>     * If there is no response, the issue will be automatically closed in 7 days.
> 
> 
> Thank you for your understanding and contribution!

Still relevant.
